In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("../data/evaluation_progress_results/all_results2.csv")

In [3]:
df.head()

,id,faithfulness,answer_relevancy,non_llm_context_precision_with_reference,context_recall,non_llm_context_recall
0,v3,0.937284,0.679021,0.903968,0.9,NaN
1,v4,0.965224,0.708957,0.940079,0.9,NaN
2,v5,0.879838,0.676309,0.925159,NaN,0.866667

In [4]:
df2=pd.read_csv("../data/evaluation_progress_results/evaluation_history2.csv")

## non_llm_context_precision_with_reference
not much may be change the embedding model

In [5]:
df2[(df2['non_llm_context_precision_with_reference']<0.95) & (df2['run_id']=="2026-07-09 20:38:47")]

,user_input,retrieved_contexts,reference_contexts,response,reference,faithfulness,answer_relevancy,non_llm_context_precision_with_reference,context_recall,run_id,non_llm_context_recall
30,What role does the Legislaive Council play in ...,['Article 243R of Indian Constitution \n: Comp...,['Article 243ZF of Indian Constitution \n: Co...,The dissolution of Municipalities is governed ...,In the case of a State having a Legislative Co...,0.785714,0.787606,0.000000,NaN,2026-07-09 20:38:47,0.000000
36,If a President also a state legislature member...,['Article 59 of Indian Constitution \n: Condi...,['<1-hop>\n\nArticle 59 of Indian Constitution...,If a state legislature member is elected Presi...,According to Article 59(1) of the Indian Const...,1.000000,0.817831,0.877381,NaN,2026-07-09 20:38:47,0.666667

In [6]:
df2.iloc[30,:]['user_input']

'What role does the Legislaive Council play in dissolving Municipalities?'

In [7]:
import ast
x=ast.literal_eval(df2.iloc[30,:]['retrieved_contexts'])
# differnt emebedding llm is a possible solution
for i in x:
    print(i)
    print()

Article 243R of Indian Constitution
: Composition of Municipalities.—
(1) Save as provided in clause (2), all the seats in a Municipality shall be filled by persons chosen by direct election from the territorial constituencies in the Municipal area and for this purpose each Municipal area shall be divided into territorial constituencies to be known as wards.
(2) The Legislature of a State may, by law, provide—
(a) for the representation in a Municipality of—
(i) persons having special knowledge or experience in Municipal administration;
(ii) the members of the House of the People and the members of the Legislative Assembly of the State representing constituencies which comprise wholly or partly the Municipal area;
(iii) the members of the Council of States and the members of the Legislative Council of the State registered as electors within the Municipal area;
(iv) the Chairpersons of the Committees constituted under clause (5) of article 243S: Provided that the persons referred to in paragraph (i) shall not have the right to vote in the meetings of the Municipality;
(b) the manner of election of the Chairperson of a Municipality.

Article 243U of Indian Constitution
: Duration of Municipalities, etc.—(1) Every Municipality, unless sooner dissolved under any law for the time being in force, shall continue for five years from the date appointed for its first meeting and no longer:
Provided that a Municipality shall be given a reasonable opportunity of being heard before its dissolution.
(2) No amendment of any law for the time being in force shall have the effect of causing dissolution of a Municipality at any level, which is functioning immediately before such amendment, till the expiration of its duration specified in clause (1).
(3) An election to constitute a Municipality shall be completed,—
(a) before the expiry of its duration specified in clause (1);
(b) before the expiration of a period of six months from the date of its dissolution: Provided that where the remainder of the period for which the dissolved Municipality would have continued is less than six months, it shall not be necessary to hold any election under this clause for constituting the Municipality for such period.
(4) A Municipality constituted upon the dissolution of a Municipality before the expiration of its duration shall continue only for the remainder of the period for which the dissolved Municipality would have continued under clause (1) had it not been so dissolved.

Article 243W of Indian Constitution
: Powers, authority and responsibilities of Municipalities, etc.— Subject to the provisions of this Constitution, the Legislature of a State may, by law, endow—
(a) the Municipalities with such powers and authority as may be necessary to enable them to function as institutions of self-government and such law may contain provisions for the devolution of powers and responsibilities upon Municipalities, subject to such conditions as may be specified therein, with respect to—
(i) the preparation of plans for economic development and social justice;
(ii) the performance of functions and the implementation of schemes as may be entrusted to them including those in relation to the matters listed in the Twelfth Schedule;
(b) the Committees with such powers and authority as may be necessary to enable them to carry out the responsibilities conferred upon them including those in relation to the matters listed in the Twelfth Schedule.

Article 243W of Indian Constitution
: Powers, authority and responsibilities of Municipalities, etc.— Subject to the provisions of this Constitution, the Legislature of a State may, by law, endow—
(a) the Municipalities with such powers and authority as may be necessary to enable them to function as institutions of self-government and such law may contain provisions for the devolution of powers and responsibilities upon Municipalities, subject to such conditions as may be specified therein, with respect to—
(i) the preparation of plans for economic development and social justice;
(ii) the performance of functions and the implementation of schemes as may be entrusted to them including those in relation to the matters listed in the Twelfth Schedule;
(b) the Committees with such powers and authority as may be necessary to enable them to carry out the responsibilities conferred upon them including those in relation to the matters listed in the Twelfth Schedule.

Article 243U of Indian Constitution
: Duration of Municipalities, etc.—(1) Every Municipality, unless sooner dissolved under any law for the time being in force, shall continue for five years from the date appointed for its first meeting and no longer:
Provided that a Municipality shall be given a reasonable opportunity of being heard before its dissolution.
(2) No amendment of any law for the time being in force shall have the effect of causing dissolution of a Municipality at any level, which is functioning immediately before such amendment, till the expiration of its duration specified in clause (1).
(3) An election to constitute a Municipality shall be completed,—
(a) before the expiry of its duration specified in clause (1);
(b) before the expiration of a period of six months from the date of its dissolution: Provided that where the remainder of the period for which the dissolved Municipality would have continued is less than six months, it shall not be necessary to hold any election under this clause for constituting the Municipality for such period.
(4) A Municipality constituted upon the dissolution of a Municipality before the expiration of its duration shall continue only for the remainder of the period for which the dissolved Municipality would have continued under clause (1) had it not been so dissolved.

Article 243R of Indian Constitution
: Composition of Municipalities.—
(1) Save as provided in clause (2), all the seats in a Municipality shall be filled by persons chosen by direct election from the territorial constituencies in the Municipal area and for this purpose each Municipal area shall be divided into territorial constituencies to be known as wards.
(2) The Legislature of a State may, by law, provide—
(a) for the representation in a Municipality of—
(i) persons having special knowledge or experience in Municipal administration;
(ii) the members of the House of the People and the members of the Legislative Assembly of the State representing constituencies which comprise wholly or partly the Municipal area;
(iii) the members of the Council of States and the members of the Legislative Council of the State registered as electors within the Municipal area;
(iv) the Chairpersons of the Committees constituted under clause (5) of article 243S: Provided that the persons referred to in paragraph (i) shall not have the right to vote in the meetings of the Municipality;
(b) the manner of election of the Chairperson of a Municipality.

In [8]:
x=ast.literal_eval(df2.iloc[30,:]['reference_contexts'])
for i in x:
    print(i)

Article 243ZF of Indian Constitution
:  Continuance of existing laws and Municipalities.—Notwithstanding anything in this Part, any provision of any law relating to Municipalities in force in a State immediately before the commencement of the Constitution (Seventy-fourth Amendment) Act, 1992, which is inconsistent with the provisions of this Part, shall continue to be in force until amended or repealed by a competent Legislature or other competent authority or until the expiration of one year from such commencement, whichever is earlier:
Provided that all the Municipalities existing immediately before such commencement shall continue till the expiration of their duration, unless sooner dissolved by a resolution passed to that effect by the Legislative Assembly of that State or, in the case of a State having a Legislative Council, by each House of the Legislature of that State.

In [9]:
df2.iloc[36,:]['user_input']

'If a President also a state legislature member, what happens to his seat and what penalty if he sits in legislature after?'

In [10]:
import ast
set(ast.literal_eval(df2.iloc[36,:]['retrieved_contexts']))

{'Article 104 of Indian Constitution \n: Penalty for sitting and voting before making oath or affirmation under article 99 or when not qualified or when disqualified.—If a person sits or votes as a member of either House of Parliament before he has complied with the requirements of article 99, or when he knows that he is not qualified or that he is disqualified for membership thereof, or that he is prohibited from so doing by the provisions of any law made by Parliament, he shall be liable in respect of each day on which he so sits or votes to a penalty of five hundred rupees to be recovered as a debt due to the Union.\n\xa0Powers, Privileges and Immunities of Parliament and its Members',
 'Article 191 of Indian Constitution \n: Disqualifications for membership.—\n(1) A person shall be disqualified for being chosen as, and for being, a member of the Legislative Assembly or Legislative Council of a State—\n[(a) if he holds any office of profit under the Government of India or the Government of any State specified in the First Schedule, other than an office declared by the Legislature of the State by law not to disqualify its holder;]\n(b) if he is of unsound mind and stands so declared by a competent court;\n(c) if he is an undischarged insolvent;\n(d) if he is not a citizen of India, or has voluntarily acquired the citizenship of a foreign State, or is under any acknowledgment of allegiance or adherence to a foreign State;\n(e) if he is so disqualified by or under any law made by Parliament.\n[Explanation.—For the purposes of this clause], a person shall not be deemed to hold an office of profit under the Government of India or the Government of any State specified in the First Schedule by reason only\xa0 that he is a Minister either for the Union or for such State.\n[(2) A person shall be disqualified for being a member of the Legislative Assembly or Legislative Council of a State if he is so disqualified under the Tenth Schedule.]',
 'Article 193 of Indian Constitution \n: Penalty for sitting and voting before making oath or affirmation under article 188 or when not qualified or when disqualified.—If a person sits or votes as a member of the Legislative Assembly or the Legislative Council of a State before he has complied with the requirements of article 188, or when he knows that he is not qualified or that he is disqualified for membership thereof, or that he is prohibited from so doing by the provisions of any law made by Parliament or the Legislature of the State, he shall be liable in respect of each day on which he so sits or votes to a penalty of five hundred rupees to be recovered as a debt due to the State.',
 'Article 59 of Indian Constitution \n:  Conditions of President’s office.—\n(1) The President shall not be a member of either House of Parliament or of a House of the Legislature of any State, and if a member of either House of Parliament or of a House of the Legislature of any State be elected President, he shall be deemed to have vacated his seat in that House on the date on which he enters upon his office as President.\n(2) The President shall not hold any other office of profit.\n(3) The President shall be entitled without payment of rent to the use of his official residences and shall be also entitled to such emoluments, allowances and privileges as may be determined by Parliament by law and, until provision in that behalf is so made, such emoluments, allowances and privileges as are specified in the Second Schedule.\n(4) The emoluments and allowances of the President shall not be diminished during his term of office.'}

In [11]:
ast.literal_eval(df2.iloc[36,:]['reference_contexts'])

['<1-hop>\n\nArticle 59 of Indian Constitution \n:  Conditions of President’s office.—\n(1) The President shall not be a member of either House of Parliament or of a House of the Legislature of any State, and if a member of either House of Parliament or of a House of the Legislature of any State be elected President, he shall be deemed to have vacated his seat in that House on the date on which he enters upon his office as President.\n(2) The President shall not hold any other office of profit.\n(3) The President shall be entitled without payment of rent to the use of his official residences and shall be also entitled to such emoluments, allowances and privileges as may be determined by Parliament by law and, until provision in that behalf is so made, such emoluments, allowances and privileges as are specified in the Second Schedule.\n(4) The emoluments and allowances of the President shall not be diminished during his term of office.',
 '<2-hop>\n\nArticle 183 of Indian Constitution \n: Vacation and resignation of, and removal from, the offices of Chairman and Deputy Chairman.—A member holding office as Chairman or Deputy Chairman of a Legislative Council—\n(a) shall vacate his office if he ceases to be a member of the Council;\n(b) may at any time by writing under his hand addressed, if such member is the Chairman, to the Deputy Chairman, and if such member is the Deputy Chairman, to the Chairman, resign his office; and\n(c) may be removed from his office by a resolution of the Council passed by a majority of all the then members of the Council:\nProvided that no resolution for the purpose of clause (c) shall be moved unless at least fourteen days‘ notice has been given of the intention to move the resolution.',
 '<3-hop>\n\nArticle 193 of Indian Constitution \n: Penalty for sitting and voting before making oath or affirmation under article 188 or when not qualified or when disqualified.—If a person sits or votes as a member of the Legislative Assembly or the Legislative Council of a State before he has complied with the requirements of article 188, or when he knows that he is not qualified or that he is disqualified for membership thereof, or that he is prohibited from so doing by the provisions of any law made by Parliament or the Legislature of the State, he shall be liable in respect of each day on which he so sits or votes to a penalty of five hundred rupees to be recovered as a debt due to the State.']

# answer relevancy

### -> our answers are difficult to understand (more formal , legal ) as compared to reference.
### -> instruct llm to stay grounded but dont add any citation or use knowledge from its training data.
### -> instruct llm to answer users query directly and use same terms as the question, in the same order, with no supporting citations unless requested
### -> keep the tone simple but answer should direclty answer the user's query .

In [12]:
df2[(df2['answer_relevancy']<0.95) & (df2['run_id']=="2026-07-09 20:38:47")]

,user_input,retrieved_contexts,reference_contexts,response,reference,faithfulness,answer_relevancy,non_llm_context_precision_with_reference,context_recall,run_id,non_llm_context_recall
30,What role does the Legislaive Council play in ...,['Article 243R of Indian Constitution \n: Comp...,['Article 243ZF of Indian Constitution \n: Co...,The dissolution of Municipalities is governed ...,In the case of a State having a Legislative Co...,0.785714,0.787606,0.000000,NaN,2026-07-09 20:38:47,0.000000
31,"As a Municipal Affairs Legal Advisor, could yo...","['IPC Section 134 - Abetment of such assault, ...","['IPC Section 134 - Abetment of such assault, ...",IPC Section 134 criminalizes the abetment of a...,IPC Section 134 states that whoever abets an a...,0.818182,0.595131,1.000000,NaN,2026-07-09 20:38:47,1.000000
32,What Article 156 say about Governor term?,['Article 156 of Indian Constitution \n: Term ...,['Article 156 of Indian Constitution \n: Term ...,Article 156(1) states the Governor holds offic...,Article 156 says the Governor holds office dur...,1.000000,0.738437,1.000000,NaN,2026-07-09 20:38:47,1.000000
33,What does IPC Section 46 define?,"['IPC Section 46 - ""Death"" \nThe word ?death? ...","['IPC Section 46 - ""Death"" \nThe word ?death? ...",IPC Section 46 defines 'death' as denoting the...,"IPC Section 46 defines the word ""death"" as den...",1.000000,0.819831,1.000000,NaN,2026-07-09 20:38:47,1.000000
34,What IPC 281 say?,"['IPC Section 281 - Exhibition of false light,...","['IPC Section 281 - Exhibition of false light,...",IPC Section 281 criminalizes the exhibition of...,IPC Section 281 says that whoever exhibits any...,1.000000,0.767422,1.000000,NaN,2026-07-09 20:38:47,1.000000
35,If a client is charged under IPC Section 413 f...,['IPC Section 413 - Habitually dealing in stol...,['<1-hop>\n\nIPC Section 413 - Habitually deal...,For IPC Section 413 (habitual dealing in stole...,For the charge under IPC Section 413 (habitual...,1.000000,0.638233,1.000000,NaN,2026-07-09 20:38:47,0.666667
36,If a President also a state legislature member...,['Article 59 of Indian Constitution \n: Condi...,['<1-hop>\n\nArticle 59 of Indian Constitution...,If a state legislature member is elected Presi...,According to Article 59(1) of the Indian Const...,1.000000,0.817831,0.877381,NaN,2026-07-09 20:38:47,0.666667
37,What are the key differences between IPC Secti...,['IPC Section 369 - Kidnapping or abducting ch...,['<1-hop>\n\nIPC Section 423 - Dishonest or fr...,"The key differences between IPC Sections 423, ...",IPC Section 423 deals with dishonest or fraudu...,1.000000,0.819341,1.000000,NaN,2026-07-09 20:38:47,1.000000
38,If a client is charged with possessing a false...,['IPC Section 266 - Being in possession of fal...,['<1-hop>\n\nIPC Section 266 - Being in posses...,The key differences between IPC 266 and IPC 42...,For the offense under IPC Section 266 (possess...,0.875000,0.536694,1.000000,NaN,2026-07-09 20:38:47,0.666667
39,"As a Municipal Affairs Legal Advisor, explain ...",['Article 191 of Indian Constitution \n: Disqu...,['<1-hop>\n\nArticle 243ZF of Indian Constitut...,Article 191 (disqualifications for state legis...,Article 243ZF of the Indian Constitution provi...,0.857143,0.561671,1.000000,NaN,2026-07-09 20:38:47,1.000000
40,How does Article 142 of the Indian Constitutio...,['Article 142 of Indian Constitution \n: Enfor...,['<1-hop>\n\nArticle 142 of Indian Constitutio...,Article 142(1) empowers the Supreme Court to p...,Article 142(1) empowers the Supreme Court to p...,1.000000,0.857237,1.000000,NaN,2026-07-09 20:38:47,1.000000
41,"So like, if a Bill gets passed by Parliament a...",['Article 111 of Indian Constitution \n: Assen...,['<1-hop>\n\nArticle 111 of Indian Constitutio...,"Under Article 111 of the Indian Constitution, ...",According to Article 111 of the Indian Constit...,1.000000,0.631340,1.000000,NaN,2026-07-09 20:38:47,1.000000
42,Wat is Article 330 of the Indian Constitution ...,['Article 330 of Indian Constitution \n: Reser...,['<1-hop>\n\nArticle 330 of Indian Constitutio...,Article 330 of the Indian Constitution mandate...,Article 330 of the Indian Constitution is abou...,1.000000,0.857185,1.000000,NaN,2026-07-09 20:38:47,1.000000
43,What is the constitutional provision under Art...,['Article 302 of Indian Constitution \n: Power...,['<1-hop>\n\nArticle 302 of Indian Constitutio...,Article 302 of the Indian Constitution empower...,Article 302 of the Indian Constitution grants ...,0.461538,0.000000,1.000000,NaN,2026-07-09 20:38:47,1.000000
44,What does Section 75 of the IPC say about enha...,['IPC Section 75 - Enhanced punishment for cer...,['<1-hop>\n\nIPC Section 75 - Enhanced punishm...,Section 75 of the Indian Penal Code provides e...,IPC Section 75 provides for enhanced punishmen...,0.400000,0.716677,1.000000,NaN,2026-07-09 20:38:47,1.000000

In [13]:
df2.iloc[31,:]['user_input']

'As a Municipal Affairs Legal Advisor, could you explain the legal implications of IPC Section 134 regarding abetment of assault within the armed forces?'

In [14]:
df2.iloc[31,:]['response']

"IPC Section 134 criminalizes the abetment of assault by military personnel (officer/soldier/sailor/airman) against a superior officer actively performing official duties. Key implications include: (1) Applies exclusively to abetment within India's Army, Navy, or Air Force [IPC 134]; (2) Requires proof that the assault occurred due to the instigation/abetment [IPC 134]; (3) Superior officer must be engaged in official duties during the assault [IPC 134 in Simple Words]; (4) Conviction carries imprisonment up to 7 years and/or fines [IPC 134]. This provision reinforces military discipline by penalizing external interference in chain-of-command relationships."

In [15]:
df2.iloc[31,:]['reference']

'IPC Section 134 states that whoever abets an assault by an officer, soldier, sailor, or airman in the Army, Navy, or Air Force of the Government of India on any superior officer being in the execution of his office shall, if such assault is committed in consequence of that abetment, be punished with imprisonment of either description for a term which may extend to seven years and shall also be liable to a fine. In simple terms, if someone encourages an officer, soldier, sailor, or airman to assault a superior officer while the superior officer is performing their duties, and the assault occurs as a result, the abettor can be punished with up to seven years in jail and a fine.'

In [16]:
df2.iloc[32,:]['user_input']

'What Article 156 say about Governor term?'

In [17]:
df2.iloc[32,:]['response']

"Article 156(1) states the Governor holds office during the President's pleasure, meaning the President can remove them at any time. Article 156(3) specifies a normal term of five years from assuming office, with a proviso that the Governor continues in office beyond this term until their successor assumes charge. The Governor may resign under Article 156(2) by submitting written resignation to the President."

In [18]:
df2.iloc[32,:]['reference']

'Article 156 says the Governor holds office during the pleasure of the President. The Governor can resign by writing to the President. Subject to these provisions, a Governor holds office for a term of five years from the date he enters upon his office. However, even after his term expires, he continues to hold office until his successor enters upon the office.'

In [19]:
df2.iloc[33,:]['user_input']

'What does IPC Section 46 define?'

In [20]:
df2.iloc[33,:]['response']

"IPC Section 46 defines 'death' as denoting the death of a human being unless the context indicates a different interpretation (IPC Section 46)."

In [21]:
df2.iloc[33,:]['reference']

'IPC Section 46 defines the word "death" as denoting the death of a human being unless the contrary appears from the context.'

In [22]:
df2.iloc[34,:]['user_input']

'What IPC 281 say?'

In [23]:
df2.iloc[34,:]['response']

'IPC Section 281 criminalizes the exhibition of false lights, marks, or buoys intended to mislead navigators. The offense is punishable with imprisonment up to seven years, a fine, or both. This applies when the perpetrator intentionally displays such false navigational aids or knows they are likely to mislead those navigating vessels (IPC Section 281).'

In [24]:
df2.iloc[34,:]['reference']

'IPC Section 281 says that whoever exhibits any false light, mark or buoy, intending or knowing it to be likely that such exhibition will mislead any navigator, shall be punished with imprisonment of either description for a term which may extend to seven years, or with fine, or with both. In simple words, if anyone displays a false light, mark, or buoy with the intention to mislead navigators, they can be punished with imprisonment for up to seven years, or a fine, or both.'

In [25]:
df2.iloc[35,:]['user_input']

'If a client is charged under IPC Section 413 for habitual dealing in stolen property and also faces a separate charge under IPC Section 498 for enticing a married woman, what are the maximum imprisonment terms for each offense, and which offense carries the potential for life imprisonment?'

In [26]:
df2.iloc[35,:]['response']

'For IPC Section 413 (habitual dealing in stolen property), the maximum imprisonment is life imprisonment or up to ten years, with a fine (Ranjitsing Brahmajeetsing vs State Of Maharashtra, Rakesh Kumar Paul vs State Of Assam). For IPC Section 498 (enticing a married woman), the maximum imprisonment is two years, with a fine or both (Vikas vs State Of Rajasthan, Athul Rao vs State Of Karnataka). Only IPC Section 413 carries the potential for life imprisonment.'

In [28]:
df2.iloc[35,:]['reference']

'For the charge under IPC Section 413 (habitually dealing in stolen property), the maximum punishment is imprisonment for life, or imprisonment for a term which may extend to ten years, along with a fine. For the charge under IPC Section 498 (enticing or taking away a married woman with criminal intent), the maximum punishment is imprisonment for a term which may extend to two years, or a fine, or both. The offense under IPC Section 413 carries the potential for life imprisonment.'

In [29]:
set(ast.literal_eval(df2.iloc[35,:]['retrieved_contexts']))

{'IPC Section 413 - Habitually dealing in stolen property \nWhoever habitually receives or deals in property which he knows or has reason to believe to be stolen property, shall be punished with imprisonment for life, or with imprisonment of either description for a term which may extend to ten years, and shall also be liable to fine.\n \nIPC 413 in Simple Words\nIf someone regularly receives or trades stolen property knowing that it is stolen, they can be punished with imprisonment for life or up to ten years, and may also face a fine.\n\nCited by\n\n\n Ranjitsing Brahmajeetsing vs State Of Maharashtra and Anr\n\n\n Rakesh Kumar Paul vs State Of Assam\n\n\n Dharminder Singh at Vijay Singh vs State\n\n\n Ram Naresh Prasad vs State Of Jharkhand and Ors\n\n\n Vaman Narain Ghiya vs State Of Rajasthan',
 'IPC Section 498 - Enticing or taking away or detaining with criminal intent a married woman \nWhoever takes or entices away any woman who is and whom he knows or has reason to believe to be the wife of any other man, from that man, or from any person having the care of her on behalf of that man, with intent that she may have illicit intercourse with any person, or conceals or detains with that intent any such woman, shall be punished with imprisonment of either description for a term which may extend to two years, or with fine, or with both.\n \nIPC 498 in Simple Words\nIf someone takes or lures away a woman who they know is married to another man, with the intention that she engages in illicit relations with anyone else, or if they hide or detain her with that intention, they can be punished with imprisonment for up to two years, a fine, or both.\n\nCited by\n\n\n Vikas vs State Of Rajasthan\n\n\n Athul Rao vs State Of Karnataka\n\n\n Jayaram Vithoba And Another vs The State Of Bombay\n\n\n Gurcharan Singh and Ors vs State Delhi Administration\n\n\n Joseph Shine vs Union Of India'}

In [30]:
df2.iloc[38,:]['user_input']

'If a client is charged with possessing a false weight under IPC 266 and also with forging a deed under IPC 423, what are the key differences in the fraudulent intent and punishment for these two offenses?'

In [32]:
print(df2.iloc[38,:]['response'])

The key differences between IPC 266 and IPC 423 are:

1. Fraudulent Intent:
- IPC 266: Requires possession of false weights/measures with intent to use them fraudulently in trade (deception through measurement manipulation) [IPC 266].
- IPC 423: Involves dishonest execution of property transfer deeds containing false consideration/beneficiary details (documentary fraud affecting property rights) [IPC 423].

2. Punishment:
- IPC 266: Maximum 1 year imprisonment, fine, or both [IPC 266].
- IPC 423: Maximum 2 years imprisonment, fine, or both [IPC 423].

IPC 423 carries greater severity in punishment due to its focus on property-related documentary fraud, while IPC 266 addresses commercial measurement fraud.

In [33]:
print(df2.iloc[38,:]['reference'])

For the offense under IPC Section 266 (possession of false weight or measure), the fraudulent intent is specifically for the instrument to be used fraudulently, and the punishment is imprisonment up to one year, or a fine, or both. For the offense under IPC Section 423 (dishonest or fraudulent execution of a deed), the fraudulent intent relates to signing a document containing a false statement about consideration or beneficiaries, and the punishment is imprisonment up to two years, or a fine, or both. The key differences are the nature of the fraudulent act (using a false instrument vs. executing a false document) and the maximum imprisonment term (one year vs. two years).

In [34]:
df2.iloc[43,:]['user_input']

"What is the constitutional provision under Article 302 of the Indian Constitution regarding Parliament's power to impose restrictions on trade and commerce, and how does this relate to the broader framework of municipal governance and compliance with state laws?"

In [35]:
print(df2.iloc[43,:]['response'])

Article 302 of the Indian Constitution empowers Parliament to impose legislative restrictions on trade, commerce, and intercourse between states or within any part of India when required in the public interest (Article 302 text). While the provision itself focuses exclusively on parliamentary authority, its implementation inherently impacts municipal governance and state law compliance through constitutional hierarchy. Parliamentary laws enacted under Article 302 would supersede conflicting municipal regulations or state trade laws under the supremacy of Union legislation in India's federal structure. However, the constitutional text provided does not detail specific mechanisms for municipal-level implementation or direct references to state law compliance procedures - these operational aspects would depend on broader constitutional principles beyond the explicit wording of Article 302.

In [36]:
print(df2.iloc[43,:]['reference'])

Article 302 of the Indian Constitution grants Parliament the power to impose restrictions on the freedom of trade, commerce, or intercourse between one State and another or within any part of the territory of India, provided such restrictions are required in the public interest and are imposed by law. This provision is a key constitutional authority that legal advisors on municipal affairs must consider when ensuring municipal governance and compliance with state laws, as it establishes Parliament's overarching legislative power to regulate economic activity in the public interest across state boundaries and within the national territory.