In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("../data/evaluation_progress.csv")

In [3]:
df.head()

,question,answer,contexts,ground_truth,persona,query_style,synthesizer
0,What role does the Legislaive Council play in ...,**Direct Answer:**\nThe provided contexts do n...,"[""Source - https://testbook.com/question-answe...",In the case of a State having a Legislative Co...,Municipal Affairs Legal Advisor,MISSPELLED,single_hop_specific_query_synthesizer
1,"As a Municipal Affairs Legal Advisor, could yo...",**Direct Answer:**\nSection 134 of the Indian ...,"[""IPC Section 134 - Abetment of such assault, ...",IPC Section 134 states that whoever abets an a...,Municipal Affairs Legal Advisor,PERFECT_GRAMMAR,single_hop_specific_query_synthesizer
2,What Article 156 say about Governor term?,**Direct Answer:**\nArticle 156 of the Constit...,"[""Article 156 of Indian Constitution \n: Term ...",Article 156 says the Governor holds office dur...,Municipal Affairs Legal Advisor,POOR_GRAMMAR,single_hop_specific_query_synthesizer
3,What does IPC Section 46 define?,**Direct Answer**\nSection 46 of the Indian Pe...,"[""IPC Section 46 - \""Death\"" \nThe word ?death...","IPC Section 46 defines the word ""death"" as den...",Municipal Affairs Legal Advisor,MISSPELLED,single_hop_specific_query_synthesizer
4,What IPC 281 say?,**Direct Answer:**\nSection 281 of the Indian ...,"[""IPC Section 281 - Exhibition of false light,...",IPC Section 281 says that whoever exhibits any...,Nandini Sharma,POOR_GRAMMAR,single_hop_specific_query_synthesizer

In [ ]:
import ast

df['contexts'].apply(lambda x: len(ast.literal_eval(x)))
# no of web search queries are too high can be a reason for lower context precision

0     9
1     2
2     1
3     1
4     1
5     2
6     5
7     3
8     3
9     9
10    1
11    1
12    1
13    2
14    1
Name: contexts, dtype: int64

In [ ]:
df2=pd.read_csv("../data/results.csv")
df2

# Observations & improvments
## Context recall is low only when we used web_search otherwise it is high => optimise web_search_query node
##

,user_input,retrieved_contexts,response,reference,faithfulness,answer_relevancy,context_precision,context_recall
0,What role does the Legislaive Council play in ...,['Source - https://testbook.com/question-answe...,**Direct Answer:**\nThe provided contexts do n...,In the case of a State having a Legislative Co...,0.811321,0.773327,0.142857,0.000000
1,"As a Municipal Affairs Legal Advisor, could yo...","['IPC Section 134 - Abetment of such assault, ...",**Direct Answer:**\nSection 134 of the Indian ...,IPC Section 134 states that whoever abets an a...,0.736842,0.513331,1.000000,1.000000
2,What Article 156 say about Governor term?,['Article 156 of Indian Constitution \n: Term ...,**Direct Answer:**\nArticle 156 of the Constit...,Article 156 says the Governor holds office dur...,0.944444,0.886083,1.000000,1.000000
3,What does IPC Section 46 define?,"['IPC Section 46 - ""Death"" \nThe word ?death? ...",**Direct Answer**\nSection 46 of the Indian Pe...,"IPC Section 46 defines the word ""death"" as den...",0.333333,0.725100,1.000000,1.000000
4,What IPC 281 say?,"['IPC Section 281 - Exhibition of false light,...",**Direct Answer:**\nSection 281 of the Indian ...,IPC Section 281 says that whoever exhibits any...,0.740741,0.704323,1.000000,1.000000
5,If a client is charged under IPC Section 413 f...,['IPC Section 413 - Habitually dealing in stol...,**Direct Answer**\nFor the charge under **Sect...,For the charge under IPC Section 413 (habitual...,0.909091,0.828754,0.000000,1.000000
6,If a President also a state legislature member...,['Article 191 of Indian Constitution \n: Disqu...,**Direct Answer:**\n\nAccording to the Constit...,According to Article 59(1) of the Indian Const...,0.923077,0.829178,0.000000,1.000000
7,What are the key differences between IPC Secti...,['IPC Section 423 - Dishonest or fraudulent ex...,**Direct Answer:**\n\nThe key differences lie ...,IPC Section 423 deals with dishonest or fraudu...,1.000000,0.969938,0.000000,1.000000
8,If a client is charged with possessing a false...,['IPC Section 266 - Being in possession of fal...,**Direct Answer**\nThe key differences lie in ...,For the offense under IPC Section 266 (possess...,0.972973,0.612299,0.000000,1.000000
9,"As a Municipal Affairs Legal Advisor, explain ...","[""Source - https://www.lexhorizon.in/post/supr...","As a Municipal Affairs Legal Advisor, I will a...",Article 243ZF of the Indian Constitution provi...,0.769231,0.000000,0.142857,0.166667
10,How does Article 142 of the Indian Constitutio...,['Article 142 of Indian Constitution \n: Enfor...,Article 142 of the Constitution of India grant...,Article 142(1) empowers the Supreme Court to p...,1.000000,0.839135,1.000000,1.000000
11,"So like, if a Bill gets passed by Parliament a...",['Article 111 of Indian Constitution \n: Assen...,"Article 111 of the Constitution, titled ""Assen...",According to Article 111 of the Indian Constit...,1.000000,0.707135,1.000000,1.000000
12,Wat is Article 330 of the Indian Constitution ...,['Article 330 of Indian Constitution \n: Reser...,Article 330 of the Constitution of India provi...,Article 330 of the Indian Constitution is abou...,1.000000,0.826866,1.000000,1.000000
13,What is the constitutional provision under Art...,['Article 302 of Indian Constitution \n: Power...,The constitutional provision under **Article 3...,Article 302 of the Indian Constitution grants ...,0.962963,0.000000,1.000000,0.500000
14,What does Section 75 of the IPC say about enha...,['IPC Section 75 - Enhanced punishment for cer...,Section 75 of the Indian Penal Code (IPC) prov...,IPC Section 75 provides for enhanced punishmen...,0.840000,0.615463,1.000000,1.000000

In [ ]:
df2.iloc[5,:]['user_input']

'If a client is charged under IPC Section 413 for habitual dealing in stolen property and also faces a separate charge under IPC Section 498 for enticing a married woman, what are the maximum imprisonment terms for each offense, and which offense carries the potential for life imprisonment?'

In [18]:
ast.literal_eval(df2.iloc[5,:]['retrieved_contexts'])

['IPC Section 413 - Habitually dealing in stolen property \nWhoever habitually receives or deals in property which he knows or has reason to believe to be stolen property, shall be punished with imprisonment for life, or with imprisonment of either description for a term which may extend to ten years, and shall also be liable to fine.\n \nIPC 413 in Simple Words\nIf someone regularly receives or trades stolen property knowing that it is stolen, they can be punished with imprisonment for life or up to ten years, and may also face a fine.\n\nCited by\n\n\n Ranjitsing Brahmajeetsing vs State Of Maharashtra and Anr\n\n\n Rakesh Kumar Paul vs State Of Assam\n\n\n Dharminder Singh at Vijay Singh vs State\n\n\n Ram Naresh Prasad vs State Of Jharkhand and Ors\n\n\n Vaman Narain Ghiya vs State Of Rajasthan',
 'IPC Section 498 - Enticing or taking away or detaining with criminal intent a married woman \nWhoever takes or entices away any woman who is and whom he knows or has reason to believe to be the wife of any other man, from that man, or from any person having the care of her on behalf of that man, with intent that she may have illicit intercourse with any person, or conceals or detains with that intent any such woman, shall be punished with imprisonment of either description for a term which may extend to two years, or with fine, or with both.\n \nIPC 498 in Simple Words\nIf someone takes or lures away a woman who they know is married to another man, with the intention that she engages in illicit relations with anyone else, or if they hide or detain her with that intention, they can be punished with imprisonment for up to two years, a fine, or both.\n\nCited by\n\n\n Vikas vs State Of Rajasthan\n\n\n Athul Rao vs State Of Karnataka\n\n\n Jayaram Vithoba And Another vs The State Of Bombay\n\n\n Gurcharan Singh and Ors vs State Delhi Administration\n\n\n Joseph Shine vs Union Of India']

In [19]:
df2.iloc[5,:]['response']

'**Direct Answer**\nFor the charge under **Section 413 of the IPC** (habitually dealing in stolen property), the maximum punishment is "imprisonment for life, or with imprisonment of either description for a term which may extend to ten years, and shall also be liable to fine" (Section 413 of the IPC).\n\nFor the charge under **Section 498 of the IPC** (enticing a married woman with criminal intent), the maximum punishment is "imprisonment of either description for a term which may extend to two years, or with fine, or with both" (Section 498 of the IPC).\n\n**Explanation**\n\n*   **IPC Section 413**: This section targets the professional or habitual trade in stolen goods. It applies to a person who "habitually receives or deals" in property they know or have reason to believe is stolen. The law imposes severe penalties to deter this organized criminal activity. The punishment scale includes the possibility of life imprisonment, which is the most severe custodial sentence under Indian law, or a prison term of up to ten years, along with a potential monetary fine.\n\n*   **IPC Section 498**: This section protects the marital relationship from external interference with a specific illicit purpose. The offense is committed when a person takes, entices away, conceals, or detains a woman he knows to be another man\'s wife. Crucially, this act must be done "with intent that she may have illicit intercourse with any person." The punishment is less severe than for Section 413, with a maximum imprisonment term of two years, and the court has the option to impose only a fine or both imprisonment and a fine.\n\n**Related Provisions & Conclusion**\nThe contexts do not provide any specific exceptions or explanations for these sections beyond the statutory text quoted.\n\nTo answer the specific parts of your query:\n1.  **Maximum Imprisonment Terms**:\n    *   IPC Section 413: Up to ten years imprisonment, with life imprisonment as the maximum possible sentence.\n    *   IPC Section 498: Up to two years imprisonment.\n2.  **Offense Carrying Potential for Life Imprisonment**: Only the charge under **IPC Section 413** (habitually dealing in stolen property) carries the potential punishment of imprisonment for life.'

In [20]:
df2.iloc[6,:]['user_input']

'If a President also a state legislature member, what happens to his seat and what penalty if he sits in legislature after?'

In [21]:
ast.literal_eval(df2.iloc[6,:]['retrieved_contexts'])

['Article 191 of Indian Constitution \n: Disqualifications for membership.—\n(1) A person shall be disqualified for being chosen as, and for being, a member of the Legislative Assembly or Legislative Council of a State—\n[(a) if he holds any office of profit under the Government of India or the Government of any State specified in the First Schedule, other than an office declared by the Legislature of the State by law not to disqualify its holder;]\n(b) if he is of unsound mind and stands so declared by a competent court;\n(c) if he is an undischarged insolvent;\n(d) if he is not a citizen of India, or has voluntarily acquired the citizenship of a foreign State, or is under any acknowledgment of allegiance or adherence to a foreign State;\n(e) if he is so disqualified by or under any law made by Parliament.\n[Explanation.—For the purposes of this clause], a person shall not be deemed to hold an office of profit under the Government of India or the Government of any State specified in the First Schedule by reason only\xa0 that he is a Minister either for the Union or for such State.\n[(2) A person shall be disqualified for being a member of the Legislative Assembly or Legislative Council of a State if he is so disqualified under the Tenth Schedule.]',
 'Article 102 of Indian Constitution \n: Disqualifications for membership.—\n(1) A person shall be disqualified for being chosen as, and for being, a member of either House of Parliament—\n[(a) if he holds any office of profit under the Government of India or the Government of any State, other than an office declared by Parliament by law not to disqualify its holder;]\n(b) if he is of unsound mind and stands so declared by a competent court;\n(c) if he is an undischarged insolvent;\n(d) if he is not a citizen of India, or has voluntarily acquired the citizenship of a foreign State, oris under any acknowledgment of allegiance or adherence to a foreign State;\n(e) if he is so disqualified by or under any law made by Parliament.\n[Explanation.—For the purposes of this clause a person shall not be deemed to hold an office of profit under the Government of India or the Government of any State by reason only that he is a Minister either for the Union or for such State.]\n[(2) A person shall be disqualified for being a member of either House of Parliament if he is so disqualified under the Tenth Schedule.]',
 'Article 59 of Indian Constitution \n:  Conditions of President’s office.—\n(1) The President shall not be a member of either House of Parliament or of a House of the Legislature of any State, and if a member of either House of Parliament or of a House of the Legislature of any State be elected President, he shall be deemed to have vacated his seat in that House on the date on which he enters upon his office as President.\n(2) The President shall not hold any other office of profit.\n(3) The President shall be entitled without payment of rent to the use of his official residences and shall be also entitled to such emoluments, allowances and privileges as may be determined by Parliament by law and, until provision in that behalf is so made, such emoluments, allowances and privileges as are specified in the Second Schedule.\n(4) The emoluments and allowances of the President shall not be diminished during his term of office.',
 'Article 193 of Indian Constitution \n: Penalty for sitting and voting before making oath or affirmation under article 188 or when not qualified or when disqualified.—If a person sits or votes as a member of the Legislative Assembly or the Legislative Council of a State before he has complied with the requirements of article 188, or when he knows that he is not qualified or that he is disqualified for membership thereof, or that he is prohibited from so doing by the provisions of any law made by Parliament or the Legislature of the State, he shall be liable in respect of each day on which he so sits or votes to a penalty of five hundred rupees to be recovered as a debt due to the State.',
 'Article 104 of Indian Constitution \n: Penalty for sitting and voting before making oath or affirmation under article 99 or when not qualified or when disqualified.—If a person sits or votes as a member of either House of Parliament before he has complied with the requirements of article 99, or when he knows that he is not qualified or that he is disqualified for membership thereof, or that he is prohibited from so doing by the provisions of any law made by Parliament, he shall be liable in respect of each day on which he so sits or votes to a penalty of five hundred rupees to be recovered as a debt due to the Union.\n\xa0Powers, Privileges and Immunities of Parliament and its Members']

In [23]:
df2.iloc[6,:]['response']

'**Direct Answer:**\n\nAccording to the Constitution of India, if a member of a State Legislature is elected as the President, their seat in the State Legislature is automatically vacated. Specifically, Article 59(1) of the Constitution states: "The President shall not be a member of either House of Parliament or of a House of the Legislature of any State, and if a member of either House of Parliament or of a House of the Legislature of any State be elected President, he shall be deemed to have vacated his seat in that House on the date on which he enters upon his office as President." [Article 59 of Indian Constitution]\n\nIf such a person, after becoming President, sits or votes in the State Legislature, they are liable to a penalty. Article 193 of the Constitution states: "If a person sits or votes as a member of the Legislative Assembly or the Legislative Council of a State... when he knows that he is not qualified or that he is disqualified for membership thereof... he shall be liable in respect of each day on which he so sits or votes to a penalty of five hundred rupees to be recovered as a debt due to the State." [Article 193 of Indian Constitution]\n\n**Explanation:**\n\n1.  **Vacation of Seat:** The office of the President is a full-time constitutional position of the highest authority. To ensure the President\'s independence and avoid any conflict of interest, the Constitution mandates that the President cannot simultaneously hold a seat in any other legislature (Parliament or State Legislature). Therefore, Article 59(1) creates an automatic legal consequence: the moment a sitting MP or MLA/MLC enters the office of President (i.e., takes the oath), their legislative seat is considered vacated by law, even if no formal resignation is submitted.\n\n2.  **Disqualification & Penalty:** The President, by virtue of holding that office, is disqualified from being a member of a State Legislature. This disqualification aligns with the general disqualification under Article 191(1)(a) for holding "any office of profit under the Government of India" (the President\'s office is such an office). [Article 191 of Indian Constitution]. If the President were to sit or vote in the legislature despite knowing this disqualification, they would be violating the Constitution. Article 193 imposes a financial penalty for such an act—Rs. 500 for each day they sit or vote while disqualified. This penalty is recoverable by the State government as if it were a debt owed by the individual.\n\n**Related Provisions:**\n\n*   **Disqualification for Parliament:** The same principle applies to a member of Parliament elected as President. Article 59(1) also covers vacation of a Parliamentary seat. The corresponding penalty for sitting or voting in Parliament while disqualified is provided in Article 104, which also prescribes a penalty of five hundred rupees per day, recoverable as a debt due to the Union. [Article 104 of Indian Constitution]\n*   **Office of Profit:** The Explanation to Article 191(1) clarifies that a Union or State Minister is not considered to hold an "office of profit" for disqualification purposes. This exception, however, does not extend to the office of the President. [Article 191 of Indian Constitution]\n*   **Conditions of President\'s Office:** Article 59(2) further reinforces the separation by stating that "The President shall not hold any other office of profit." [Article 59 of Indian Constitution]'

In [24]:
df2.iloc[7,:]['user_input']

'What are the key differences between IPC Section 423, IPC Section 407, and IPC Section 369 regarding the nature of the dishonest act and the maximum imprisonment term?'

In [25]:
ast.literal_eval(df2.iloc[7,:]['retrieved_contexts'])

['IPC Section 423 - Dishonest or fraudulent execution of deed of transfer containing false statement of consideration \nWhoever dishonestly or fraudulently signs, executes or becomes a party to any deed or instrument which purports to transfer or subject to any charge any property, or any interest therein, and which contains any false statement relating to the consideration for such transfer or charge, or relating to the person or persons for whose use or benefit it is really intended to operate, shall be punished with imprisonment of either description for a term which may extend to two years, or with fine, or with both.\n \nIPC 423 in Simple Words\nIf someone dishonestly signs or participates in a document that transfers or charges property, and that document contains false information about the consideration or the intended beneficiaries, they can be punished with imprisonment up to two years, or fined, or both.',
 'IPC Section 407 - Criminal breach of trust by carrier, etc. \nWhoever, being entrusted with property as a carrier, wharfinger or warehouse-keeper, commits criminal breach of trust, in respect of such property, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.\n \nIPC 407 in Simple Words\nIf a carrier, wharfinger, or warehouse-keeper betrays the trust placed in them and commits criminal breach of trust with the property they were entrusted with, they can be punished with imprisonment for up to seven years, along with a fine.\n\nCited by\n\n\n Tarkeshwar Sahu vs State Of Bihar Now Jharkhand\n\n\n All Cargo Movers I Pvt Ltd and Ors vs Dhanesh Badarmal Jain and Anr\n\n\n Ram Narain Popli vs Central Bureau Of Investigation\n\n\n Sanjay Raghunath Agarwal vs The Directorate Of Enforcement\n\n\n M N Damani vs S K Sinha And Others',
 'IPC Section 369 - Kidnapping or abducting child under ten years with intent to steal from its person \nWhoever kidnaps or abducts any child under the age of ten years with the intention of taking dishonestly any movable property from the person of such child, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.\n \nIPC 369 in Simple Words\nIn the Indian Penal Code, anyone who kidnaps a child under ten years of age with the intention of dishonestly taking their property can be punished with imprisonment for up to seven years and fined.']

In [26]:
df2.iloc[8,:]['user_input']

'If a client is charged with possessing a false weight under IPC 266 and also with forging a deed under IPC 423, what are the key differences in the fraudulent intent and punishment for these two offenses?'

In [27]:
ast.literal_eval(df2.iloc[8,:]['retrieved_contexts'])

['IPC Section 266 - Being in possession of false weight or measure \nWhoever is in possession of any instrument for weighing, or of any weight, or of any measure of length or capacity, which he knows to be false, intending that the same may be fraudulently used, shall be punished with imprisonment of either description for a term which may extend to one year, or with fine, or with both.\n \nIPC 266 in Simple Words\nAccording to section 266 of the Indian Penal Code, if someone possesses a false weighing instrument, weight, or measure with the intention of using it fraudulently, they can be punished with imprisonment up to one year or with a fine or both.',
 'IPC Section 423 - Dishonest or fraudulent execution of deed of transfer containing false statement of consideration \nWhoever dishonestly or fraudulently signs, executes or becomes a party to any deed or instrument which purports to transfer or subject to any charge any property, or any interest therein, and which contains any false statement relating to the consideration for such transfer or charge, or relating to the person or persons for whose use or benefit it is really intended to operate, shall be punished with imprisonment of either description for a term which may extend to two years, or with fine, or with both.\n \nIPC 423 in Simple Words\nIf someone dishonestly signs or participates in a document that transfers or charges property, and that document contains false information about the consideration or the intended beneficiaries, they can be punished with imprisonment up to two years, or fined, or both.',
 'IPC Section 24 - Dishonestly \nWhoever does anything with the intention of causing wrongful gain to one person or wrongful loss to another person, is said to do that thing “dishonestly”.']