In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("../data/evaluation_progress_results/all_results2.csv")

In [3]:
df.head()

,id,faithfulness,answer_relevancy,non_llm_context_precision_with_reference,context_recall
0,v3,0.937284,0.679021,0.903968,0.9

In [6]:
df2=pd.read_csv("../data/evaluation_progress_results/evaluation_history2.csv")

In [7]:
df2.sort_values("user_input")

,user_input,retrieved_contexts,reference_contexts,response,reference,faithfulness,answer_relevancy,non_llm_context_precision_with_reference,context_recall,run_id
1,"As a Municipal Affairs Legal Advisor, could yo...","['IPC Section 134 - Abetment of such assault, ...","['IPC Section 134 - Abetment of such assault, ...","Based solely on the provided contexts, as a Mu...",IPC Section 134 states that whoever abets an a...,0.703704,0.524967,1.000000,1.0,2026-07-09 16:10:58
9,"As a Municipal Affairs Legal Advisor, explain ...",['Article 243ZF of Indian Constitution \n: Co...,['<1-hop>\n\nArticle 243ZF of Indian Constitut...,"As a Municipal Affairs Legal Advisor, I will a...",Article 243ZF of the Indian Constitution provi...,0.970588,0.685340,1.000000,0.5,2026-07-09 16:10:58
10,How does Article 142 of the Indian Constitutio...,['Article 142 of Indian Constitution \n: Enfor...,['<1-hop>\n\nArticle 142 of Indian Constitutio...,Article 142 of the Constitution of India empow...,Article 142(1) empowers the Supreme Court to p...,1.000000,0.870356,1.000000,1.0,2026-07-09 16:10:58
6,If a President also a state legislature member...,['Article 59 of Indian Constitution \n: Condi...,['<1-hop>\n\nArticle 59 of Indian Constitution...,The query has two parts: (1) what happens to a...,According to Article 59(1) of the Indian Const...,0.833333,0.904791,0.642857,0.5,2026-07-09 16:10:58
5,If a client is charged under IPC Section 413 f...,['IPC Section 498 - Enticing or taking away or...,['<1-hop>\n\nIPC Section 413 - Habitually deal...,Based on the provided contexts from the Indian...,For the charge under IPC Section 413 (habitual...,1.000000,0.679181,1.000000,1.0,2026-07-09 16:10:58
8,If a client is charged with possessing a false...,['IPC Section 25 - Fraudulently \nA person is ...,['<1-hop>\n\nIPC Section 266 - Being in posses...,The key differences between the offenses under...,For the offense under IPC Section 266 (possess...,0.896552,0.617564,0.500000,1.0,2026-07-09 16:10:58
11,"So like, if a Bill gets passed by Parliament a...",['Article 111 of Indian Constitution \n: Assen...,['<1-hop>\n\nArticle 111 of Indian Constitutio...,Based on the provided context from Article 111...,According to Article 111 of the Indian Constit...,0.772727,0.796596,1.000000,1.0,2026-07-09 16:10:58
12,Wat is Article 330 of the Indian Constitution ...,['Article 330 of Indian Constitution \n: Reser...,['<1-hop>\n\nArticle 330 of Indian Constitutio...,Article 330 of the Constitution of India conce...,Article 330 of the Indian Constitution is abou...,1.000000,0.821754,1.000000,1.0,2026-07-09 16:10:58
2,What Article 156 say about Governor term?,['Article 156 of Indian Constitution \n: Term ...,['Article 156 of Indian Constitution \n: Term ...,Article 156 of the Constitution of India stipu...,Article 156 says the Governor holds office dur...,1.000000,0.840338,1.000000,1.0,2026-07-09 16:10:58
4,What IPC 281 say?,"['IPC Section 281 - Exhibition of false light,...","['IPC Section 281 - Exhibition of false light,...","Section 281 of the IPC is titled ""Exhibition o...",IPC Section 281 says that whoever exhibits any...,1.000000,0.756913,1.000000,1.0,2026-07-09 16:10:58
7,What are the key differences between IPC Secti...,['IPC Section 423 - Dishonest or fraudulent ex...,['<1-hop>\n\nIPC Section 423 - Dishonest or fr...,"Based on the provided contexts, here are the k...",IPC Section 423 deals with dishonest or fraudu...,1.000000,1.000000,1.000000,1.0,2026-07-09 16:10:58
3,What does IPC Section 46 define?,"['IPC Section 46 - ""Death"" \nThe word ?death? ...","['IPC Section 46 - ""Death"" \nThe word ?death? ...","IPC Section 46 defines the term ""death"". Accor...","IPC Section 46 defines the word ""death"" as den...",1.000000,1.000000,1.000000,1.0,2026-07-09 16:10:58
14,What does Section 75 of the IPC say about enha...,['IPC Section 75 - Enhanced punishment for cer...,['<1-hop>\n\nIPC Section 75 - Enhanced punishm...,Section 75 of the Indian Penal Code (IPC) prov...,IPC Section 75 provides for enhanced punishmen...,0.882353,0.687514,1.000000,1.0,2026-07-09 16:10:58
13,What is the constitutional provision under Art...,['Article 302 of Indian Constitution \n: Power...,['<1-hop>\n\nArticle 302 of Indian Constitutio...,The constitutional provision under Article 302...,Article 302 of the Indian Constitution grants ...,1.000000,0.000000,1.000000,0.5,2026-07-09 16:10:58
0,What role does the Legislaive Council play in ...,['Article 243W of Indian Constitution \n: Powe...,['Article 243ZF of Indian Constitution \n: Co...,The role of the Legislative Council in dissolv...,In the case of a State having a Legislative Co...,1.000000,0.000000,0.416667,1.0,2026-07-09 16:10:58

In [ ]:
df2.iloc[1,:]['user_input']

'As a Municipal Affairs Legal Advisor, could you explain the legal implications of IPC Section 134 regarding abetment of assault within the armed forces?'

In [ ]:
print(df2.iloc[1,:]['retrieved_contexts'])

['IPC Section 134 - Abetment of such assault, if the assault committed \nWhoever abets an assault by an officer, soldier, sailor, or airman in the Army, Navy, or Air Force of the Government of India on any superior officer being in the execution of his office shall, if such assault is committed in consequence of that abetment, be punished with imprisonment of either description for a term which may extend to seven years and shall also be liable to a fine.\nIPC 134 in Simple Words\nIf someone encourages an officer, soldier, sailor, or airman to assault a superior officer while the superior officer is performing their duties, and the assault occurs as a result, the abettor can be punished with up to seven years in jail and a fine.', 'IPC Section 134 - Abetment of such assault, if the assault committed \nWhoever abets an assault by an officer, soldier, sailor, or airman in the Army, Navy, or Air Force of the Government of India on any superior officer being in the execution of his office shall, if such assault is committed in consequence of that abetment, be punished with imprisonment of either description for a term which may extend to seven years and shall also be liable to a fine.\nIPC 134 in Simple Words\nIf someone encourages an officer, soldier, sailor, or airman to assault a superior officer while the superior officer is performing their duties, and the assault occurs as a result, the abettor can be punished with up to seven years in jail and a fine.']

In [ ]:
print(df2.iloc[1,:]['response'])

Based solely on the provided contexts, as a Municipal Affairs Legal Advisor, I can provide the following explanation of the legal implications of Section 134 of the Indian Penal Code (IPC).

**1. The Offence:** Section 134 of the IPC criminalizes the abetment of an assault by a member of the armed forces on a superior officer. The offence is defined as follows: "Whoever abets an assault by an officer, soldier, sailor, or airman in the Army, Navy, or Air Force of the Government of India on any superior officer being in the execution of his office shall, if such assault is committed in consequence of that abetment, be punished with imprisonment of either description for a term which may extend to seven years and shall also be liable to a fine." (Section 134 of the IPC).

**2. Key Legal Implications and Elements:**
    *   **Abetment:** The core of the offence is the act of abetment. The provided contexts do not define the specific legal meaning of "abetment" as used in this section.
    *   **Perpetrator:** The actual assault must be committed by an "officer, soldier, sailor, or airman" from the Indian Army, Navy, or Air Force.
    *   **Victim:** The victim must be a "superior officer" of the perpetrator and must be "in the execution of his office" at the time of the assault.
    *   **Causation:** A critical condition for the offence to be complete is that the assault must be committed "in consequence of that abetment." The abetment must be a direct cause of the assault.
    *   **Punishment:** If convicted, the abettor faces imprisonment (simple or rigorous) for a term extending up to seven years, along with a potential fine.

**3. Context for a Municipal Affairs Advisor:** While this section of the IPC deals specifically with discipline within the national armed forces, its principles of abetment and liability are relevant in a broader municipal legal context. Municipal authorities often deal with public order, and understanding the legal framework for abetting offences is crucial. However, it is important to note that Section 134 itself applies only to the specific scenario involving the armed forces. The general law on abetment is covered under other sections of the IPC.

**Limitations:** The provided contexts contain only the text of Section 134 and a simple paraphrase. They do not contain any judicial interpretations, definitions of "abetment" or "superior officer," or related constitutional provisions (e.g., Article 33) that may govern the armed forces. Therefore, a comprehensive legal analysis, including defenses, procedural aspects, or interplay with military law, cannot be provided from the given material.

In [11]:
print(df2.iloc[1,:]['reference'])

IPC Section 134 states that whoever abets an assault by an officer, soldier, sailor, or airman in the Army, Navy, or Air Force of the Government of India on any superior officer being in the execution of his office shall, if such assault is committed in consequence of that abetment, be punished with imprisonment of either description for a term which may extend to seven years and shall also be liable to a fine. In simple terms, if someone encourages an officer, soldier, sailor, or airman to assault a superior officer while the superior officer is performing their duties, and the assault occurs as a result, the abettor can be punished with up to seven years in jail and a fine.

In [26]:
import ast
ast.literal_eval(df2.iloc[1,:]['retrieved_contexts'])

['IPC Section 134 - Abetment of such assault, if the assault committed \nWhoever abets an assault by an officer, soldier, sailor, or airman in the Army, Navy, or Air Force of the Government of India on any superior officer being in the execution of his office shall, if such assault is committed in consequence of that abetment, be punished with imprisonment of either description for a term which may extend to seven years and shall also be liable to a fine.\nIPC 134 in Simple Words\nIf someone encourages an officer, soldier, sailor, or airman to assault a superior officer while the superior officer is performing their duties, and the assault occurs as a result, the abettor can be punished with up to seven years in jail and a fine.',
 'IPC Section 133 - Abetment of assault by soldier, sailor or airman on his superior officer, when in execution of his office \nWhoever abets an assault by an officer, soldier, sailor or airman, in the Army, Navy or Air Force of the Government of India, on any superior officer being in the execution of his office, shall be punished with imprisonment of either description for a term which may extend to three years, and shall also be liable to fine.\nIPC 133 in Simple Words\nIf someone encourages an officer, soldier, sailor, or airman to assault a superior officer while the superior officer is performing their duties, the abettor can be punished with up to three years in jail and a fine.']

In [13]:
df2.iloc[20,:]['user_input']

'If a client is charged under IPC Section 413 for habitual dealing in stolen property and also faces a separate charge under IPC Section 498 for enticing a married woman, what are the maximum imprisonment terms for each offense, and which offense carries the potential for life imprisonment?'

In [14]:
ast.literal_eval(df2.iloc[5,:]['retrieved_contexts'])

['IPC Section 413 - Habitually dealing in stolen property \nWhoever habitually receives or deals in property which he knows or has reason to believe to be stolen property, shall be punished with imprisonment for life, or with imprisonment of either description for a term which may extend to ten years, and shall also be liable to fine.\n \nIPC 413 in Simple Words\nIf someone regularly receives or trades stolen property knowing that it is stolen, they can be punished with imprisonment for life or up to ten years, and may also face a fine.\n\nCited by\n\n\n Ranjitsing Brahmajeetsing vs State Of Maharashtra and Anr\n\n\n Rakesh Kumar Paul vs State Of Assam\n\n\n Dharminder Singh at Vijay Singh vs State\n\n\n Ram Naresh Prasad vs State Of Jharkhand and Ors\n\n\n Vaman Narain Ghiya vs State Of Rajasthan',
 'IPC Section 498 - Enticing or taking away or detaining with criminal intent a married woman \nWhoever takes or entices away any woman who is and whom he knows or has reason to believe to be the wife of any other man, from that man, or from any person having the care of her on behalf of that man, with intent that she may have illicit intercourse with any person, or conceals or detains with that intent any such woman, shall be punished with imprisonment of either description for a term which may extend to two years, or with fine, or with both.\n \nIPC 498 in Simple Words\nIf someone takes or lures away a woman who they know is married to another man, with the intention that she engages in illicit relations with anyone else, or if they hide or detain her with that intention, they can be punished with imprisonment for up to two years, a fine, or both.\n\nCited by\n\n\n Vikas vs State Of Rajasthan\n\n\n Athul Rao vs State Of Karnataka\n\n\n Jayaram Vithoba And Another vs The State Of Bombay\n\n\n Gurcharan Singh and Ors vs State Delhi Administration\n\n\n Joseph Shine vs Union Of India']

In [15]:
df2.iloc[23,:]['user_input']

'If a client is charged with possessing a false weight under IPC 266 and also with forging a deed under IPC 423, what are the key differences in the fraudulent intent and punishment for these two offenses?'

In [16]:
ast.literal_eval(df2.iloc[23,:]['retrieved_contexts'])

['IPC Section 266 - Being in possession of false weight or measure \nWhoever is in possession of any instrument for weighing, or of any weight, or of any measure of length or capacity, which he knows to be false, intending that the same may be fraudulently used, shall be punished with imprisonment of either description for a term which may extend to one year, or with fine, or with both.\n \nIPC 266 in Simple Words\nAccording to section 266 of the Indian Penal Code, if someone possesses a false weighing instrument, weight, or measure with the intention of using it fraudulently, they can be punished with imprisonment up to one year or with a fine or both.',
 'IPC Section 25 - Fraudulently \nA person is said to do a thing fraudulently if he does that thing with intent to defraud but not otherwise.',
 'IPC Section 423 - Dishonest or fraudulent execution of deed of transfer containing false statement of consideration \nWhoever dishonestly or fraudulently signs, executes or becomes a party to any deed or instrument which purports to transfer or subject to any charge any property, or any interest therein, and which contains any false statement relating to the consideration for such transfer or charge, or relating to the person or persons for whose use or benefit it is really intended to operate, shall be punished with imprisonment of either description for a term which may extend to two years, or with fine, or with both.\n \nIPC 423 in Simple Words\nIf someone dishonestly signs or participates in a document that transfers or charges property, and that document contains false information about the consideration or the intended beneficiaries, they can be punished with imprisonment up to two years, or fined, or both.',
 'IPC Section 463 - Forgery \nWhoever makes any false document or part of a document with intent to cause damage or injury, to the public or to any person, or to support any claim or title, or to cause any person to part with property, or to enter into any express or implied contract, or with intent to commit fraud or that fraud may be committed, commits forgery.\n \nIPC 463 in Simple Words\nForgery is committed when someone creates a false document or part of a document with the intention to cause harm, deceive others, support a claim, acquire property, or engage in fraudulent activities.']

In [24]:
df2.iloc[7,:]['user_input']

'What are the key differences between IPC Section 423, IPC Section 407, and IPC Section 369 regarding the nature of the dishonest act and the maximum imprisonment term?'

In [25]:
ast.literal_eval(df2.iloc[7,:]['retrieved_contexts'])

['IPC Section 423 - Dishonest or fraudulent execution of deed of transfer containing false statement of consideration \nWhoever dishonestly or fraudulently signs, executes or becomes a party to any deed or instrument which purports to transfer or subject to any charge any property, or any interest therein, and which contains any false statement relating to the consideration for such transfer or charge, or relating to the person or persons for whose use or benefit it is really intended to operate, shall be punished with imprisonment of either description for a term which may extend to two years, or with fine, or with both.\n \nIPC 423 in Simple Words\nIf someone dishonestly signs or participates in a document that transfers or charges property, and that document contains false information about the consideration or the intended beneficiaries, they can be punished with imprisonment up to two years, or fined, or both.',
 'IPC Section 407 - Criminal breach of trust by carrier, etc. \nWhoever, being entrusted with property as a carrier, wharfinger or warehouse-keeper, commits criminal breach of trust, in respect of such property, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.\n \nIPC 407 in Simple Words\nIf a carrier, wharfinger, or warehouse-keeper betrays the trust placed in them and commits criminal breach of trust with the property they were entrusted with, they can be punished with imprisonment for up to seven years, along with a fine.\n\nCited by\n\n\n Tarkeshwar Sahu vs State Of Bihar Now Jharkhand\n\n\n All Cargo Movers I Pvt Ltd and Ors vs Dhanesh Badarmal Jain and Anr\n\n\n Ram Narain Popli vs Central Bureau Of Investigation\n\n\n Sanjay Raghunath Agarwal vs The Directorate Of Enforcement\n\n\n M N Damani vs S K Sinha And Others',
 'IPC Section 369 - Kidnapping or abducting child under ten years with intent to steal from its person \nWhoever kidnaps or abducts any child under the age of ten years with the intention of taking dishonestly any movable property from the person of such child, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.\n \nIPC 369 in Simple Words\nIn the Indian Penal Code, anyone who kidnaps a child under ten years of age with the intention of dishonestly taking their property can be punished with imprisonment for up to seven years and fined.']

In [26]:
df2.iloc[8,:]['user_input']

'If a client is charged with possessing a false weight under IPC 266 and also with forging a deed under IPC 423, what are the key differences in the fraudulent intent and punishment for these two offenses?'

In [27]:
ast.literal_eval(df2.iloc[8,:]['retrieved_contexts'])

['IPC Section 266 - Being in possession of false weight or measure \nWhoever is in possession of any instrument for weighing, or of any weight, or of any measure of length or capacity, which he knows to be false, intending that the same may be fraudulently used, shall be punished with imprisonment of either description for a term which may extend to one year, or with fine, or with both.\n \nIPC 266 in Simple Words\nAccording to section 266 of the Indian Penal Code, if someone possesses a false weighing instrument, weight, or measure with the intention of using it fraudulently, they can be punished with imprisonment up to one year or with a fine or both.',
 'IPC Section 423 - Dishonest or fraudulent execution of deed of transfer containing false statement of consideration \nWhoever dishonestly or fraudulently signs, executes or becomes a party to any deed or instrument which purports to transfer or subject to any charge any property, or any interest therein, and which contains any false statement relating to the consideration for such transfer or charge, or relating to the person or persons for whose use or benefit it is really intended to operate, shall be punished with imprisonment of either description for a term which may extend to two years, or with fine, or with both.\n \nIPC 423 in Simple Words\nIf someone dishonestly signs or participates in a document that transfers or charges property, and that document contains false information about the consideration or the intended beneficiaries, they can be punished with imprisonment up to two years, or fined, or both.',
 'IPC Section 24 - Dishonestly \nWhoever does anything with the intention of causing wrongful gain to one person or wrongful loss to another person, is said to do that thing “dishonestly”.']

In [30]:
df2.iloc[0,:]['user_input']

'What role does the Legislaive Council play in dissolving Municipalities?'

In [39]:
from langchain_core.messages import HumanMessage, SystemMessage

_r1_kwargs = dict(
    model="us.deepseek.r1-v1:0",
    api_key=os.environ['AWS_BEARER_TOKEN_BEDROCK'],
    region_name="us-east-1",
)

model=ChatBedrockConverse(**_r1_kwargs, temperature=1)

In [42]:
sys_prompt=SystemMessage(content=f"""You are an expert legal AI Assistant specializing in the Indian Penal Code (IPC) and the
Constitution of India. Your task is to analyze the user's query and determine the most appropriate retrieval method.

CONTEXT ON THE INTERNAL VECTOR DATABASE:
The internal vector store contains the full, up-to-date text of two official legal documents (as amended by the Government of India to date), chunked and embedded for semantic search:
1. Indian Penal Code (IPC), 1860 - all chapters and sections (e.g., Section 302 - Murder, Section 420 - Cheating), including section numbers, headings, current statutory text, illustrations, and explanations/exceptions attached to each section, reflecting all amendments made to date.
2. Constitution of India - all Articles (e.g., Article 21 - Right to Life, Article 14 - Equality before law), reflecting all constitutional amendments made to date.

Each chunk is indexed with metadata such as document type (IPC/Constitution), section/article number, chapter/part name, and title, allowing accurate semantic and keyword-style retrieval for queries about the definition, wording, punishment, scope, rights, or duties as they currently stand in law (post-amendments), as stored in the vector database. Note: this store does NOT contain case law, judicial interpretations, or news about pending/proposed amendments not yet enacted.

ROUTING RULES:
- Choose 'retrieval' if the query asks about the definition, current text, punishment, scope, or wording of a specific IPC section or Constitutional article/part — including its current (amended) form.
- Choose 'retrieval' if the query asks you to COMPARE, CONTRAST, or REASON ABOUT THE RELATIONSHIP between two or more provisions that are themselves fully contained in the store. This applies even when the query uses language like "interaction," "conflict," "overlap," "tension," or "adjudicate" .
- If a jurisdiction-conferring article (e.g., Article 138, Article 131, Article 226) is mentioned only to ask about the SCOPE of that provision itself, not about a specific past exercise of it, treat that portion as 'retrieval' too.
- Choose 'web_search' if the query requires current events, recent Supreme Court/High Court judgments, ongoing legal proceedings, news, proposed-but-not-yet-enacted amendments, or any information beyond the static enacted text stored in the vector database.
- Choose 'None' if the query is a greeting, casual remark, or does not require any external document or web information to be answered.

TIEBREAKER RULES:
- If a query could plausibly require both the statutory text AND recent developments (e.g., asking about the current/live status of a provision or dispute), choose 'web_search'.
- If a query asks for a relationship, comparison, or reasoned synthesis between two or more provisions without referencing a specific ongoing dispute, live status, or named case, prefer 'retrieval'.
- When in doubt between 'retrieval' and 'None', prefer 'retrieval'.
""")

human_promt=HumanMessage(content="What role does the Legislaive Council play in dissolving Municipalities?")

res=model.invoke([sys_prompt,human_promt])

In [44]:
res.content

[{'type': 'text',
  'text': '\n\n**Step-by-Step Analysis:**\n\n1. **Query Focus:** The query asks about the constitutional role of the Legislative Council (a state-level body in bicameral legislatures) in dissolving municipalities. This relates to the **Constitution of India**, specifically provisions about state legislatures and local self-government (municipalities).\n\n2. **Constitutional Provisions Involved:**\n   - **Part IXA (Articles 243P-243ZG):** Deals with municipalities. Article 243Q empowers state legislatures to constitute municipalities, but dissolution mechanisms are typically governed by state laws enacted under this framework.\n   - **Article 169:** Allows states to create/abolish Legislative Councils, but does not directly address municipalities.\n   - **State List (Seventh Schedule):** Local government (including municipalities) is a state subject (Entry 5), so state legislatures (including Legislative Councils, where they exist) have legislative authority.\n\n3. **Retrieval Relevance:** The query requires analyzing:\n   - Whether the **Constitution** explicitly grants Legislative Councils a role in dissolving municipalities.\n   - The general legislative process for state laws (including those affecting municipalities) under **Articles 196-198** (procedure for passing bills in states with Legislative Councils).\n\n4. **Web Search Exclusion:** The query does not ask for recent cases, pending amendments, or political disputes. It focuses on the constitutional/statutory framework, which is fully covered in the vector database.\n\n**Conclusion:** Use **retrieval** to fetch relevant constitutional articles (e.g., Part IXA, Articles 196-198) and explain the Legislative Council’s role in the legislative process for state laws governing municipalities.'},
 {'type': 'reasoning_content',
  'reasoning_content': {'text': 'Okay, let\'s break down the user\'s query: "What role does the Legislative Council play in dissolving Municipalities?" \n\nFirst, I need to determine if this relates to the IPC or the Constitution of India. The Legislative Council is part of the state legislature in bicameral states, so this is a constitutional matter. The dissolution of municipalities would likely involve constitutional articles related to local governments, such as Part IXA (Municipalities) which includes Articles 243P to 243ZG.\n\nThe user is asking about the role of the Legislative Council in this process. I should check if the Constitution specifies the Legislative Council\'s involvement. For example, Article 243Q deals with the constitution of municipalities, but dissolution might be covered under other articles. However, the Constitution typically outlines the structure and powers, so the Legislative Council\'s role would be part of the legislative process, perhaps in passing laws related to municipalities.\n\nSince the query is about the constitutional provisions governing the Legislative Council\'s role, it falls under the Constitution of India. The internal database has the full text of the Constitution, including all articles. Therefore, retrieval is appropriate here as it\'s about the current constitutional text. There\'s no mention of recent cases or pending amendments, so web search isn\'t needed. The answer should be based on the stored constitutional articles.\n',
   'signature': ''}}]